-- 1. For each library member his card number, first, middle and last name along with the number of book copies he ever borrowed. There may be members who didn't ever borrow any book copy.
-- ------------------------------
-- WRITE_YOUR_QUERY_HERE for 1.
-- ________________________________
-- 2. Members (their card numbers, first, middle and last names) who held a book copy the longest. 
-- There can be one such member or more than one. 
-- Don't take into accout a case that someone borrowed the same book copy again.
-- Don't take into account members who borrowed a book copy and didn't return it yet.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 2.
-- ________________________________
-- 3. For each book (ISBN and title) the number of copies the library owns.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 3.
-- ________________________________
-- 4. Books (ISBNs and titles), if any, having exactly 3 authors.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 4.
-- ________________________________
-- 5. For each author (ID, first, middle and last name) the number of books he wrote.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 5.
-- ________________________________
-- 6. Card number, first, middle and last name of members, if any, who borrowed some book by Chartrand(s). 
-- Remove duplicates from the result.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 6.
-- ________________________________
-- 7. Most popular author(s) (their IDs and first, middle and last names) in the library.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 7.
-- ________________________________
-- 8. Card numbers, first, middle, last names and addresses of members whose libray card will expire within the next month.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 8.
-- ________________________________
-- 9. Card numbers, first, middle and last names of members along with the amount of money they owe to the library. 
-- Assume that if a book copy is returned one day after the due date, a member ows 0.25 cents to the library.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 9.
-- ________________________________
-- 10. The amount of money the library earned (received money for) from late returns.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 10.
-- ________________________________
-- 11. Members (their card numbers, first, middle and last names) who borrowed more non-fiction books than fiction books.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 11.
-- ________________________________
-- 12. Name of the most popular publisher(s).
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 12.
-- ________________________________
-- 13. Members (card numbers, first, middle and last names) who never borrowed any book copy and whose card expired.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 13.
-- ________________________________
-- 14. The most popular genre(s).
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 14.
-- ________________________________
-- 15. For each state, in which some member lives, the most pupular last name(s). 
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 15.
-- ________________________________
-- 16. Books (ISBNs and titles) that don't have any authors. 
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 16.
-- ________________________________
-- 17. Members (card numbers) who borrowed the same book more than once (not necessarily the same copy of a book).
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 17.
-- ________________________________
-- 18. Number of members from Cookeville, TN and from Algood, TN.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 18.
-- ________________________________
-- 19. Card numbers and emails of members who should return a book copy tomorrow. If these members didn't renew their loan twice, then they still have a chance to renew their loan. If they won't renew or return a book tomorrow, then they will be charged for the following day(s).
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 19.
-- ________________________________
-- 20. Condition of a book copy that was borrowed the most often, not necessarily held the longest.
-- --------------------------------
-- WRITE_YOUR_QUERY_HERE for 20.
-- ________________________________